Workout01-akhil-perimbeti
================
Akhil Perimbeti

Season 2017 for the GOLDEN STATE WARRIORS: An In-Depth player review.
---------------------------------------------------------------------

### A seasonal player analysis.

The 2016-2017 warriors basketball season was their best season yet, with a 4-1 lead against Cleveland. This is the 5th chanmpionship the warriors have won, setting the best postteam record in NBA history by going 16-1 with wins. The Warriors team has been supported by its main starting five players: Stephen Curry, Andre Iguodala, Kevin Durant, Draymond Green and Klay Thompson. These key players have brought in a spectacular season of basketball and this superteam continues to be on the rise.

This 2016-2017 season was also the best year for the main players on Golden State.Draymond Green won the Defensive Player of the Year Award at the NBA Awards, the first time a Warrior has won it. Kevin Durant won the NBA Finals MVP award, the third time a Warrior has won it. The Warriors won the Team of the Year Award at the Espy Awards. Durant, Stephen Curry, Klay Thompson and Draymond Green were all named to the All-Star Game, the first time Golden State have had four All-Stars and just the eighth time in NBA history a single team has had four players in the game.

In this report, we are gonna focus on the strenghts in terms of 2PT, 3PT and Overall Effective Shooting Percentage of the 5 main starters on this team and will be taking an in-depth look into the shot chart spread of various shots taken by the teams two top scorers: Steph Curry and the new addition to the Warriors, Kevin Durant.

### Wide Analysis of Percentage Effectiveness of Shots for Starters on Golden State

Shot charts for all in Golden State Warriors
--------------------------------------------

![](/Users/akhilperimbeti/Desktop/stat133/workout01/images/gsw-shot-charts.png)

The above image shows the shot chart distribution for all the starting players on the Golden State Warriors team. I will be reffering back to this chart further in my report to support certain anlalysis about certain players.

### *2PT Shot Effectiveness Percentages*

    ##   X           Name Total Made Percent_Made
    ## 1 1 Andre Iguodala   210  134     63.80952
    ## 2 2   Kevin Durant   643  390     60.65319
    ## 3 3  Stephen Curry   563  304     53.99645
    ## 4 4  Klay Thompson   640  329     51.40625
    ## 5 5 Draymond Green   346  171     49.42197

The table above shows us the data fro the 5 starters of the Golden State Warriors, ranked by 3-pt effective shooting percentage. We can see that Iguodala leads for the highest percentage of 2PT shots made, however the data is misleading because KD is acutally holds this crown. Andre Iguodala is one of Golden States' strong defensive players and so his scoring stats appear to be so high because he is shooting most of his shots off or guaranteed in-the-key shots. These conditions are favorable to a high scoring percentage. Looking at Iguodala's shot chart we can see a high concentration of made shots inside the key, supporing my analysis above. The real star here is KD who has a 60.6% success shot rate with almost 643 attempted 2PT shots. KD is extremeley consistent as we can see from his shot chart, making him the leading scorer on GSW.

### *3PT Shot Effectiveness Percentages*

    ##   X           Name Total Made Percent_Made
    ## 1 1  Klay Thompson   580  246     42.41379
    ## 2 2  Stephen Curry   687  280     40.75691
    ## 3 3   Kevin Durant   272  105     38.60294
    ## 4 4 Andre Iguodala   161   58     36.02484
    ## 5 5 Draymond Green   232   74     31.89655

The table above shows us the data fro the 5 starters of the Golden State Warriors, ranked by 3-pt effective shooting percentage. We can see that Thompson leads for % of effective shots made, however Curry has more attempted 3PT shots with a much more consistent and effective 3PT return rate than Thompson with 687 attempted 3PT shots from Curry. Curry is often the player that takes shots from all over the court(CLUTCH!) and often in the most intense parts of the game. This could account for why his shooting % is lower than Thompson's. However don't ignore Klay Thompson's performance on court. He's taken almost as many shots overall as Stephen Curry, but has a higher overall percentage. When looking at the shot chart for Thompson, we can see that Klay's 3-pointers are concentrated on the 3-point line as opposed to Curry who is all over the place.

### *Overall Effective Shooting Percentages*

    ##   X           Name Total Made Percent_Made
    ## 1 1   Kevin Durant   915  495     54.09836
    ## 2 2 Andre Iguodala   371  192     51.75202
    ## 3 3  Klay Thompson  1220  575     47.13115
    ## 4 4  Stephen Curry  1250  584     46.72000
    ## 5 5 Draymond Green   578  245     42.38754

he table above shows us the data fro the 5 starters of the Golden State Warriors, ranked by overall( including 2PT and 3PT goals) effective shooting percentage. As expected, the MVP for this season Kevin Durant holds the highest scoring pewrcentage of field goals. 54.1% success rate for all attemptes shots. We can see that the defensive players like Green and Iguodala seem to hold with their scoring percentages, but the defensive players have much less attempted shots on goal. Curry and Thompson have over 1220 shots attempted and still hold a very high success rate, indicating that they are key offensive players as well.

### *KD vs Curry*

#### Comparing the shot range effectiveness and shot distribution consistency of the two main players on GSW: Stephen Curry and Kevin Durant

#### Stephen Curry

![Always the GOAT](/Users/akhilperimbeti/Desktop/stat133/workout01/images//curry.jpg) In this section we will be looking at Steph Curry's shot chart, in order to further analyze his effective shooting percentage and why his role on the team as a point guard is cruicially attributed to the growing success the Golden State Warriors.

<img src="/Users/akhilperimbeti/Desktop/stat133/workout01/images/stephen-curry-shot-chart.png" width="80%" style="display: block; margin: auto;" /> The image above shows us all of Steph Curry's attempted and completed shots he has made this season. The red dots indicating the areas on the court where an attempted shot was taken and the green dots indicating the areas Steph has put up a shot and followed through. We can see how Curry's shooting effectiveness might look to be low when analyzing the percentages in the Overall Shooting by Player table, but don't be sleeping on Curry. From the image above, we can see that Curry's shots are much more highly concentrated outside the 3PT line, which is reason for Curry's poupluarity and key role on the team (his innate abiolity to sink 3 pointers). His 3PT effectiveness seemes to be more concentrated around the left shoulder outside the 3PT line, indicating that he has certain strong shooting spots. Curry takes much more challenging shots and holds several records surrounding 3 pointers such as: Most 3 pointers made in a game: 13, Most consecutive regular-season games with a made three-pointer: 157, Most consecutive playoff games with a made three-pointer: 75 and several more.

### Kevin Durant

![KD for another guaranteed point in the box](/Users/akhilperimbeti/Desktop/stat133/workout01/images//kd.jpg)

In this section, we'll be looking at KD's shot chart to analyze his shot for shot effectivness and analyze how the new additon of his extremely crucial role to the Golden State Warriors to see how this season's team skyrocketed the standing of the Warriors into an NBA superteam.

<img src="/Users/akhilperimbeti/Desktop/stat133/workout01/images/kevin-durant-shot-chart.png" width="80%" style="display: block; margin: auto;" /> The image above shows the density of shooting percentages of shots made by Kevin Durant. Similar to the graphic above, the green dots relate to the attempted shots that were points and the red as only attempted shots. We can see now how KD has such a high effective overall schooting percentage because as shooting guard he has a very deep consistent shot, very likely sinking a high percentage all the shots he takes inside the 3PT line. He is equally skilled on the left and right shoulders of the key, with most of his shots concentrated on the inside. He takes easy shots and his value comes from his field goal consistency making him the highest scorer on the team. He was rewarded the Most Valuable Player award and this year has been his career highest for making 55% of all shots attempted on court. He also holds the NBA record of the most consecutive regular-season games with twenty or more points: 72.

Conclusion
----------

We can see that our analysis of both players simply lead us to the conclusion that these two players are very valuable to the success of the Golden State Warriors this season. Durant and Curry might be the leaders of the team, however we cannot solely attribute the team's skyrocketing championship success to only them. Draymond Green held the record of being the first NBA player to record a triple-double while scoring fewer than ten points(12 rebounds, 10 assists, 10 steals), making him an invaluable player for the Dubs defense. Klay Thompson, the other shooting guard holds the record for being the first player to score 60 points in a game in under 30 minutes, showing his value as another key offensive player for Golden State. This team sweeped the competition this season, with their tight defense and penetrating offense and there are no doubts they will ride this wave of championship success into the 2018 season as well.

**Bibliography(sources)**

-   [2016–17 Golden State Warriors season](https://en.wikipedia.org/wiki/2016%E2%80%9317_Golden_State_Warriors_season#Roster)
-   [Steph Curry Review](https://www.goldenstateofmind.com/2017/7/31/16054192/2017-nba-warriors-steph-curry-durant-season-review)
-   [Kevin Durant MVP](https://www.goldenstateofmind.com/2017/9/9/16211440/nba-2017-golden-state-warriors-season-review-kevin-durant)
-   [2016-17 GSW records and stats](https://www.basketball-reference.com/teams/GSW/)
